### ISSUE TITLE
Where did you get the models from?

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [hawkeye64/classify#2]
If I may ask,

where did you get the `models_VGGNet_coco_SSD_512x512` for example from?
This might be a noobish question but I am usually able to find the `weights` and `prototxt` but can’t find the corresponding `coco_types.txt`.

**Comment by hawkeye64** [comment]
@ThibaultJanBeyer You know what, I can't remember. And, don't know why the `coco-types.txt` are missing. I tried looking for it. All I remember was some Caffe models on Github, that then referenced an FTP.

After looking around, I think it was one of these: https://github.com/BVLC/caffe/wiki/Model-Zoo

**Comment by hawkeye64** [comment]
Maybe here: https://pjreddie.com/projects/coco-mirror/
